import { rand } from "../Pages/utils";

export const blogHeader = {
  sectionName: "Blogs",
  id: "Blogs",
  tabs: ["Featured", "NLP", "Machine Learning", "Machine Learning Mathematics", "Programming and Others"],
  activeTab: 'Featured',
  description: "Behind the practice conveyed in these projects, [lies valuable theory] that I like to [simplify and share with others in blogs]:",
  projectExtraLinkIcon: "FaMedium",
  projectsComment: "",
  buttonText: "View Blog"
}

export const blogStyles = {
  "center": false,
  "tabUI": rand({"true":0.7, "false":0.3}),
  "showBottom": rand({"true": 0.05, "false": 0.95}),
  "theme": rand({"ClassicGrid":0.7, "ModernGrid":0.3}),
}

export const blogData = [
    {
      title: "FastSpeech: Paper Overview & Implementation",
      description: "Learn about text-to-speech and how its realized by transformers",
      image: "https://i.imgur.com/FExGNmf.png",
      link: "https://essamwissam.medium.com/fastspeech-paper-overview-implementation-e2b3808648f1",
      github_link: "https://essamwissam.medium.com/fastspeech-paper-overview-implementation-e2b3808648f1",
      categories: ["NLP", "Featured"],
    },
    {
      title: "A Systematic Explanation of Transformers",
      description: "Comes with free intuition, clarity and, comprehensiveness",
      image: "https://i.imgur.com/28kIP9I.png",
      link: "https://medium.com/@essamwissam/a-systematic-explanation-of-transformers-db82e039b913",
      github_link: "https://github.com/EssamWisam/Memoirify",
      categories: ["NLP", "Featured"],

    },
    {
      title: "Predict Tomorrow’s Apple Stocks with LSTMs",
      description: "An Introductory Article on Time Series Forecasting with LSTMs",
      image: "https://i.imgur.com/WtqCLpD.png",
      link: "https://cmp-docs.netlify.app/",
      github_link: "https://github.com/EssamWisam/cmp-docs",
      categories: ["Machine Learning"],
    },
    {
      title: "Easily Implement Multiclass SVM From Scratch in Python",
      description: "Comes with a Free Deep Overview on SVMs",
      image: "https://i.imgur.com/DznCBzh.png",
      link: "https://github.com/abdullahalshawafi/Mathemati_",
      github_link: "https://github.com/abdullahalshawafi/Mathemati_",
      categories: ["Machine Learning"],
    },
    {
      title: "Lagrange Multipliers, KKT Conditions, and Duality",
      description: "Your key to understanding SVMs, Regularization, PCA, and many other machine learning concepts.",
      image: "https://i.imgur.com/xsEoYg0.png",
      link: "https://github.com/SE-Project-CMP-Tumbler/SE-Project-CMP-Front-end",
      github_link: "https://github.com/SE-Project-CMP-Tumbler/SE-Project-CMP-Front-end",
      categories: ["Machine Learning Mathematics", "Featured"],
    },
    {
      title: "From Python to Julia: An Invitation Letter",
      description: "Warmly Extended to Python Lovers, Scientific Computing Wizards and Data Scientists",
      image: "https://i.imgur.com/4JkzVp9.png",
      link: "https://medium.com/towards-data-science/embracing-julia-an-invitation-letter-332f5709378e",
      github_link: "https://github.com/Makrion/WorldCup-2022-reservation-site",
      categories: ["Programming and Others", "Featured"],
    },
    {
      title: "From Python to Julia: An Ultimate Guide",
      description: "Transfer learning what you know as a data scientist from Python to Julia",
      image: "https://i.imgur.com/Zf3U85p.png",
      link: "https://github.com/Makrion/WorldCup-2022-reservation-site",
      github_link: "https://github.com/Makrion/WorldCup-2022-reservation-site",
      categories: ["Programming and Others", "Featured"],
    },
    {
      title: "Class Imbalance and Resampling: A Formal Introduction",
      description: "Let’s explore the class imbalance problem and how resampling methods such as random oversampling attempt to solve it.",
      image: "https://i.imgur.com/aqeFc0J.png",
      link: "https://play.google.com/store/apps/details?id=com.essamos.diary&pli=1",
      github_link: "https://github.com/EssamWisam/Daily-Chronicle-ReactNative",
      categories: ["Class Imbalance"],
    },
    {
      title: "Class Imbalance: ROSE and Random Walk Oversampling (RWO)",
      description: "Let’s formally define the class imbalance problem then intuitively derive solutions for it!",
      image: "https://i.imgur.com/G71Pxl7.png",
      link: "https://github.com/EssamWisam/Breaking-RSA-With-Math",
      github_link: "https://github.com/EssamWisam/Breaking-RSA-With-Math",
      categories: ["Class Imbalance"],
    },
    {
      title: "Class Imbalance: From SMOTE to BorderlineSMOTE1, SMOTE-NC and SMOTE-N",
      description: "Exploring three algorithms to tackle the class imbalance problem",
      image: "https://i.imgur.com/RgfOLl1.png",
      link: "https://github.com/reem-atalah/Titanic-Dispute_Assembly",
      github_link: "https://github.com/reem-atalah/Titanic-Dispute_Assembly",
      categories: ["Class Imbalance"],
    },
    {
      title: "Class Imbalance: Exploring Undersampling Techniques",
      description: "Let’s learn about undersampling and how it helps solve class imbalance",
      image: "https://i.imgur.com/RA3ebyE.png",
      link: "https://keyteachingknowledge.github.io/",
      github_link: "https://github.com/KeyTeachingKnowledge/Quizzery-React-Native",
      categories: ["Class Imbalance",],
    },
    {
      title: "Diving Deeper to Crack Google Summer of Code (GSoC)",
      description: "An exciting opportunity you should not miss",
      image: "https://i.imgur.com/DdbCJCY.png",
      link: "https://mega.nz/file/7OgABLSI#2_8Wnr3OMyXb-59oiJxyqYeTY9B2_gBFj2O1XRJRf8o",
      github_link: "https://github.com/AhmadJamal01/Galaxy-Surfers",
      categories: ["Programming and Others", "Featured"],
    },
    {
      title: "Language Modeling with LSTMs in PyTorch",
      description: "Learning how to protect their affections at the genre, an assertive case of its own,” said the model.",
      image: "https://i.imgur.com/ZGFFWvG.png",
      link: "https://github.com/EssamWisam/Sentiment-Classification-Arabic-COVID-Tweets",
      github_link: "https://github.com/EssamWisam/Sentiment-Classification-Arabic-COVID-Tweets",
      categories: ["NLP"],
    },
    {
      title: "Why do RNNs have Short-term Memory?",
      description: "All you need is a straightforward explanation",
      image: "https://i.imgur.com/cKWxn51.png",
      link: "https://github.com/TheBotiverse/Botiverse",
      github_link: "https://github.com/TheBotiverse/Botiverse",
      categories: ["NLP"],
    },
    {
      title: "Easily Understand LSTMs & GRUs",
      description: "We will proceed to prove that LSTMs & GRU are easier than you thought",
      image: "https://i.imgur.com/gjBECsF.png",
      link: "https://github.com/tactful-ai/Dstny-LLM",
      github_link: "https://github.com/tactful-ai/Dstny-LLM",
      categories: ["NLP"],
    },
    {
      title: "Demystifying Recurrent Neural Network (RNNs)",
      description: "Let’s abstract away all the abstractions and understand them for real!",
      image: "https://i.imgur.com/wnT5WwW.png",
      link: "https://github.com/radwaahmed2132000/Auto-Grader",
      github_link: "https://github.com/radwaahmed2132000/Auto-Grader",
      categories: ["NLP"],
    },
    {
      title: "Strategic Management of Machine Learning Projects",
      description: "12 Key guidelines to keep in mind before you superintend your next machine learning project",
      image: "https://i.imgur.com/tfjg11s.png",
      link: "https://github.com/radwaahmed2132000/Gender-Classification-ICDAR2013",
      github_link: "https://github.com/radwaahmed2132000/Gender-Classification-ICDAR2013",
      categories: ["Machine Learning"],
    },
    {
      title: "Logarithmic Differentiation in a Nutshell",
      description: "For final results check the first three of the last five images.",
      image: "https://i.imgur.com/zvxKiJ2.png",
      link: "https://github.com/Halahamdy22/Flood-Detection-Radar",
      github_link: "https://github.com/Halahamdy22/Flood-Detection-Radar",
      categories: ["Machine Learning Mathematics"],
    },
    {
      title: "Deriving Backpropagation with Cross-Entropy Loss",
      description: "Minimizing the loss for classification models",
      image: "https://i.imgur.com/dB82f6y.png",
      link: "https://github.com/EssamWisam/Github-Metadata-Analytics",
      github_link: "https://github.com/EssamWisam/Github-Metadata-Analytics",
      categories: ["Machine Learning Mathematics"],
    },
    {
      title: "Implementing Backpropagation From Scratch in Python 3+",
      description: "Let’s see if theory and practice are the same thing.",
      image: "https://i.imgur.com/NipNGLh.png",
      link: "https://i.imgur.com/AJRoAqQ.png",
      github_link: "https://github.com/NouranHany/Airline-Satisfaction-Predictors",
      categories: ["Machine Learning"],
    },
    {
      title: "Backpropagation: The Simple Proof",
      description: "Time to truly understand how the algorithm works.",
      image: "https://i.imgur.com/nzZaWtQ.png",
      link: "https://juliaai.github.io/Imbalance.jl/dev/",
      github_link: "https://github.com/JuliaAI/Imbalance.jl",
      categories: ["Machine Learning Mathematics"],
    },
    {
      title: "Deriving a Solution for Least Absolute Deviations",
      description: "Least absolute errors are more fair",
      image: "https://i.imgur.com/7Ga2B6e.png",
      link: "https://github.com/EssamWisam/MLPath",
      github_link: "https://github.com/EssamWisam/MLPath",
      categories: ["Machine Learning Mathematics"],
    },
    {
      title: "Why is Least Squares So Special?",
      description: "Why doesn’t anyone talk about 'absolute loss?'",
      image: "https://i.imgur.com/Qs3uCyz.png",
      link: "https://github.com/Marim1611/Bing-Bang-BodyLevel",
      github_link: "https://github.com/Marim1611/Bing-Bang-BodyLevel",
      categories: ["Machine Learning Mathematics"],
    },
    {
      title: "Deriving the Normal Equation for Ordinary Least Squares.",
      description: "This will turn out to be simpler than you think.",
      image: "https://i.imgur.com/NCFSv32.png",
      link: "https://github.com/Marim1611/Bing-Bang-BodyLevel",
      github_link: "https://github.com/Marim1611/Bing-Bang-BodyLevel",
      categories: ["Machine Learning Mathematics"],
    },
  
  ]
  